# Generated by Django 5.0.1 on 2025-07-18 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_refurbishedlaptop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='issue_description',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='device_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='refurbishedlaptop',
            old_name='title',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='refurbishedlaptop',
            old_name='description',
            new_name='specs',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='refurbishedlaptop',
            name='image',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='issue_type',
            field=models.CharField(default='Screen Repair', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refurbishedlaptop',
            name='model_name',
            field=models.CharField(default='Unknown Model', max_length=100),
            preserve_default=False,
        ),
    ]
