# Generated by Django 5.2.4 on 2025-07-19 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_booking_preferred_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='laptop_model',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(default='General Service', max_length=100),
            preserve_default=False,
        ),
    ]
