# Generated by Django 5.2.4 on 2025-07-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_booking_laptop_model_booking_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='problem_description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
    ]
