# Generated by Django 5.2.4 on 2025-07-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_booking_problem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='refurbishedlaptop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/laptop/'),
        ),
    ]
