# Generated by Django 5.2.4 on 2025-07-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_refurbishedlaptop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refurbishedlaptop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
