# Generated by Django 5.2.4 on 2025-07-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='issue_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
