# Generated by Django 5.2.4 on 2025-07-21 10:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refurbishedlaptop',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
